-- MySQL Script generated by MySQL Workbench
-- Tue 24 Oct 2017 11:01:01 PM ICT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema library_manager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `library_manager` ;

-- -----------------------------------------------------
-- Schema library_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library_manager` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`borrow_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`borrow_cards` ;

CREATE TABLE IF NOT EXISTS `mydb`.`borrow_cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_token` VARCHAR(45) NOT NULL,
  `extended_at` DATETIME NOT NULL,
  `expired_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_token_UNIQUE` (`id_token` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `display_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_private_informations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_private_informations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_private_informations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password_digest` VARCHAR(60) NOT NULL,
  `private_infor_id` INT NOT NULL,
  `card_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_name_UNIQUE` (`name` ASC),
  INDEX `fk_users_idx` (`card_id` ASC),
  INDEX `fk_role_idx` (`role_id` ASC),
  INDEX `fk_private_infor_idx` (`private_infor_id` ASC),
  UNIQUE INDEX `private_infor_id_UNIQUE` (`private_infor_id` ASC),
  UNIQUE INDEX `card_id_UNIQUE` (`card_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_borrow_card`
    FOREIGN KEY (`card_id`)
    REFERENCES `mydb`.`borrow_cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_private_infor`
    FOREIGN KEY (`private_infor_id`)
    REFERENCES `mydb`.`user_private_informations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permissions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `display_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role_permisson`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role_permisson` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role_permisson` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_permission_index` USING BTREE (`role_id` ASC, `permission_id` ASC),
  INDEX `fk_permission_idx` (`permission_id` ASC),
  CONSTRAINT `fk_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission`
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Book` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_token` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`book_copies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`book_copies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`book_copies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_token` VARCHAR(45) NOT NULL,
  `book_id` INT NOT NULL,
  `status` MEDIUMTEXT NULL,
  `is_borrowed` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_token_UNIQUE` (`id_token` ASC),
  INDEX `fk_book_idx` (`book_id` ASC),
  CONSTRAINT `fk_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`Book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`borrow_informations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`borrow_informations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`borrow_informations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creatted_at` DATETIME NOT NULL,
  `borrowed_at` DATETIME NULL,
  `returned_at` DATETIME NULL,
  `book_status_before` MEDIUMTEXT NULL,
  `book_status_after` MEDIUMTEXT NULL,
  `pre_paid_fee` VARCHAR(45) NULL,
  `borrow_fee` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`borrow_records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`borrow_records` ;

CREATE TABLE IF NOT EXISTS `mydb`.`borrow_records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `book_copy_id` INT NOT NULL,
  `progress` ENUM('registed', 'accepted', 'borrowed', 'returned') NOT NULL,
  `borrow_infor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_borrow_infor_idx` (`borrow_infor_id` ASC),
  INDEX `fk_borrower_idx` (`user_id` ASC),
  INDEX `fk_book_copy_idx` (`book_copy_id` ASC),
  CONSTRAINT `fk_borrow_infor`
    FOREIGN KEY (`borrow_infor_id`)
    REFERENCES `mydb`.`borrow_informations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borrower`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_copy`
    FOREIGN KEY (`book_copy_id`)
    REFERENCES `mydb`.`book_copies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `library_manager` ;

-- -----------------------------------------------------
-- Table `library_manager`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_manager`.`roles` ;

CREATE TABLE IF NOT EXISTS `library_manager`.`roles` (
  `roleID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`roleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_manager`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_manager`.`users` ;

CREATE TABLE IF NOT EXISTS `library_manager`.`users` (
  `userID` VARCHAR(10) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `fullname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(10) NULL,
  `contact` VARCHAR(255) NULL,
  `roleID` INT NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_role_idx` (`roleID` ASC),
  CONSTRAINT `fk_role`
    FOREIGN KEY (`roleID`)
    REFERENCES `library_manager`.`roles` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_manager`.`borrow_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_manager`.`borrow_cards` ;

CREATE TABLE IF NOT EXISTS `library_manager`.`borrow_cards` (
  `cardID` VARCHAR(10) NOT NULL,
  `expired_date` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `active_code` VARCHAR(60) NULL,
  `userID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cardID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`userID`)
    REFERENCES `library_manager`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_manager`.`hust_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_manager`.`hust_student` ;

CREATE TABLE IF NOT EXISTS `library_manager`.`hust_student` (
  `studentID` INT NOT NULL,
  `user_id` VARCHAR(10) NOT NULL,
  `student_period` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`studentID`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `library_manager`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_manager`.`books_infor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_manager`.`books_infor` ;

CREATE TABLE IF NOT EXISTS `library_manager`.`books_infor` (
  `bookID` VARCHAR(10) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `ibsn` VARCHAR(30) NOT NULL,
  `publisher` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`bookID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_manager`.`book_copies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_manager`.`book_copies` ;

CREATE TABLE IF NOT EXISTS `library_manager`.`book_copies` (
  `copy_number` INT NOT NULL,
  `bookID` VARCHAR(10) NOT NULL,
  `sequence_number` INT NOT NULL,
  `type_of_copy` VARCHAR(20) NOT NULL,
  `price` INT NOT NULL,
  `copy_status` MEDIUMTEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_borrowed` TINYINT NOT NULL,
  PRIMARY KEY (`copy_number`),
  INDEX `fk_book_idx` (`bookID` ASC),
  CONSTRAINT `fk_book`
    FOREIGN KEY (`bookID`)
    REFERENCES `library_manager`.`books_infor` (`bookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_manager`.`borrow_infor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_manager`.`borrow_infor` ;

CREATE TABLE IF NOT EXISTS `library_manager`.`borrow_infor` (
  `inforID` INT NOT NULL,
  `lent_date` DATETIME NULL,
  `expected_return_date` DATETIME NULL,
  `progress` ENUM('registerd', 'accepted', 'rejected', 'borrowed', 'returned') NOT NULL,
  `copy_status_before` VARCHAR(255) NULL,
  `copy_status_after` VARCHAR(255) NULL,
  `pre_paid_fee` INT NULL,
  `borrow_fee` INT NULL,
  PRIMARY KEY (`inforID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_manager`.`borrow_records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_manager`.`borrow_records` ;

CREATE TABLE IF NOT EXISTS `library_manager`.`borrow_records` (
  `id` INT NOT NULL,
  `cardID` VARCHAR(10) NOT NULL,
  `copy_number` INT NOT NULL,
  `inforID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_book_copy_idx` (`copy_number` ASC),
  INDEX `fk_borrow_card_idx` (`cardID` ASC),
  INDEX `fk_borrow_infor_idx` (`inforID` ASC),
  CONSTRAINT `fk_book_copy`
    FOREIGN KEY (`copy_number`)
    REFERENCES `library_manager`.`book_copies` (`copy_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borrow_card`
    FOREIGN KEY (`cardID`)
    REFERENCES `library_manager`.`borrow_cards` (`cardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borrow_infor`
    FOREIGN KEY (`inforID`)
    REFERENCES `library_manager`.`borrow_infor` (`inforID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
